{{- if .Values.ignition.redundancy.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helm.name" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: {{ include "helm.name" . }}
      {{- include "helm.selectorLabels" . | nindent 6 }}
{{- end }}
