name: Index

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  updates:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v5
        with:
          version: v3.14.4

      - name: Update Chart Dependencies
        run: sh ./.github/scripts/ci/update-dependencies.sh

      - name: Check for changes
        id: git_diff
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit and Push Changes
        if: steps.git_diff.outputs.changes_detected == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add charts/**
          if ! git diff --cached --quiet; then
            git commit -m "chore(helm): update chart lock and yaml files"
            git push
          else
            echo "No changes staged for commit."
          fi

  testing:
    needs: updates
    uses: ./.github/workflows/testing.yaml

  quality:
    needs: updates
    uses: ./.github/workflows/quality.yaml

  release:
    needs: [testing, quality]
    uses: ./.github/workflows/release.yaml
    secrets: inherit

  webpage:
    needs: release
    uses: ./.github/workflows/webpage.yaml
