name: Code Quality

on:
  workflow_call:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  kube-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v4.0.4

      - name: Render Helm Charts
        run: |
          mkdir rendered
          
          # Render Failover
          helm dependency build charts/failover
          helm template failover charts/failover > rendered/failover.yaml
          
          # Render Scaleout
          helm dependency build charts/scaleout
          helm template scaleout charts/scaleout > rendered/scaleout.yaml

      - name: Scan with kube-linter
        uses: stackrox/kube-linter-action@v1.0.7
        with:
          directory: rendered/
          format: plain

  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'config'
          scan-ref: 'charts'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  checkov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: charts/
          framework: helm
          soft_fail: false
          output_format: cli
          skip_check: CKV_K8S_21,CKV_K8S_35,CKV_K8S_22,CKV_K8S_15,CKV_K8S_38,CKV_K8S_43,CKV_K8S_40,CKV2_K8S_6
