name: Release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release.json
          manifest-file: .github/.release.json

      - name: Configure Git
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        if: ${{ steps.release.outputs.releases_created }}
        uses: azure/setup-helm@v5
        with:
          version: v3.14.4

      - name: Update dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: sh ./.github/scripts/ci/update-dependencies.sh

      - name: Run chart-releaser
        if: ${{ steps.release.outputs.releases_created }}
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          pages_branch: main
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
